### ISSUE TITLE
Adding account verification information to Account and Settings Documentation

### ISSUE THREAD

**Issue by Whatthefoxsays** [sendgrid/docs#3999]
Add the information from this FAQ page into a new "Verifying your Account" page. 

https://github.com/sendgrid/docs/blob/Whatthefoxsays-patch-15/source/Classroom/Basics/Account/account_sign_up_faq.md

Use the following format for the head matter of the page, adding your own title, SEO description, and keywords:

```
---
layout: page
weight: 0
group: account-management
title: 
seo:
  title: 
  description:
  keywords: 
navigation:
  show: true
---
```
